// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// lgammaVec
arma::vec lgammaVec(arma::vec& inVec, int G);
RcppExport SEXP _DIMMSC_lgammaVec(SEXP inVecSEXP, SEXP GSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type inVec(inVecSEXP);
    Rcpp::traits::input_parameter< int >::type G(GSEXP);
    rcpp_result_gen = Rcpp::wrap(lgammaVec(inVec, G));
    return rcpp_result_gen;
END_RCPP
}
// EM_multinomial
Rcpp::List EM_multinomial(const arma::mat& data, const int K, const arma::mat& alphaInput, const int maxiter, const double tol, const double likTol);
RcppExport SEXP _DIMMSC_EM_multinomial(SEXP dataSEXP, SEXP KSEXP, SEXP alphaInputSEXP, SEXP maxiterSEXP, SEXP tolSEXP, SEXP likTolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const int >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type alphaInput(alphaInputSEXP);
    Rcpp::traits::input_parameter< const int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type likTol(likTolSEXP);
    rcpp_result_gen = Rcpp::wrap(EM_multinomial(data, K, alphaInput, maxiter, tol, likTol));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DIMMSC_lgammaVec", (DL_FUNC) &_DIMMSC_lgammaVec, 2},
    {"_DIMMSC_EM_multinomial", (DL_FUNC) &_DIMMSC_EM_multinomial, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_DIMMSC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
