# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lgammaVec <- function(inVec, G) {
    .Call('_DIMMSC_lgammaVec', PACKAGE = 'DIMMSC', inVec, G)
}

EM_multinomial <- function(data, K, alphaInput, maxiter, tol, likTol) {
    .Call('_DIMMSC_EM_multinomial', PACKAGE = 'DIMMSC', data, K, alphaInput, maxiter, tol, likTol)
}

